---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rook-ceph
resources:
  - ./helmrelease.yaml
  - ./reweight-job.yaml
patches:
  - patch: |-
      - op: add
        path: /metadata/annotations/reloader.stakater.com~1auto
        value: "true"
    target:
      group: apps
      version: v1
      kind: Deployment
      name: rook-ceph-tools
labels:
  - pairs:
      app.kubernetes.io/name: rook-ceph-cluster
      app.kubernetes.io/instance: rook-ceph-cluster
      app.kubernetes.io/part-of: rook-ceph
