kind: Service
apiVersion: v1
metadata:
  name: portainer-agent
  namespace: portainer
spec:
  # type: LoadBalancer
  # selector:
  #   app: portainer-agent
  type: LoadBalancer
  loadBalancerIP: 10.0.10.22 # Replace with your desired static IP
  selector:
    app: portainer-agent
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9001
