---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  - ./rook-ceph-external/rook-ceph-external-vars.sops.yaml
  # Flux-Kustomizations
  - ./rook-ceph-external/ks.yaml
