# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_ID: ENC[AES256_GCM,data:sG9e8djpdOqZU4/wO3Tflv1z5hFdZB/tO3r8fBLTwn51C4ev,iv:1eahTsHY2ZTasXfDS1+cu+gDFbPtRCtioejKFkmRCSo=,tag:tVvu4Z0etWwXTyZ357Lk0Q==,type:str]
  credentials.json: ENC[AES256_GCM,data:03nVF79NmFmySEPi+rb3tEXZFiEMNKh0//Ur5K3G+WxQCo7wCRY5vHeHQynyUy2kYevH90HeBf5rbyzph+QU4jBKY2+01DzDgHUq9j1sVPbyzx3BFlcnxXiW9dQdKPDfNIQiUHxlTnMC18g9ns82ViXB5DzTpppfExqTpY/cN2XDOPDDuopLOWn/jtxRHcVfsGqx5Ph7sGJTNJ5SYz4zi5ScltcZDpxTPgOAads44w==,iv:2M8Fw1Rm/ygT2iee/8OA4xtZGtXwmf/yb4rosIFlNis=,tag:mOrwXblBBFxgTX/DYSwnxA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1vea69na6y65tv68elw68vmr5huk3ya0xf3pmrjnxp6ztdy76xfgsn02vu4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnS0NJQngwNnFXYXVPWUdz
        OWthRGFDWUVEQW5OM2pNM1RJTVBCdy9vSG1nCjl4Wm5oTnVXUDBOcmJvTmdrQmJz
        V3hBUTg2bjZFelN2RFBiNlZ2Vkl6a3MKLS0tICtacjFka1BxL0E2eGZUOTlZdnNm
        SDJqbzN2aksyS0F2SzMxQWdqTHBiRUUKVvhM2VryFwpxgrTp7rU8bdX8tLKaYYWM
        SiW4+eVxnEz3iEYjtqgkBkRM62PcWxwiv+Q/h7//z9oyvNx/+wfv1Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-20T20:28:05Z"
  mac: ENC[AES256_GCM,data:zc2RcDkwvCT1E0Paguk3agX4AwRAwl8OQJ4x6oD429McJ4chzpz0inxbIFPOCjZtovP0S3QU+pG8Nl4FekqLXAXo1NyofmpXJWhMHG/qxPdXIB55XhqPdYiQPjREFDXsYS5O7yf0+y/9P4F4Jy/u8Ejifw1eJqn5TPBOqwTxQcg=,iv:4i7K1EfynPo6z5EEpAgHQjtFWH0V6L8X/YRkcqC9frI=,tag:0OiXl7RUvEemSP/2HPe9Dw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
