# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_ID: ENC[AES256_GCM,data:iEhBJk2cepsOt6duFIYfbXKtkzIE3CAfXQAfj+UJiZeK1JT9,iv:FUtlZ0sayjAYOXSxTrG5xIzWF8CFSoQ8Z2G/UJmqd+4=,tag:OcU4d0wHNHG4cLyxXHZhiA==,type:str]
  credentials.json: ENC[AES256_GCM,data:GkZ3oRsOPjLQf9TL1cSJmnCvFT/byGioU4DJBT4kQsp08uTvw38MJbjLFDT5BGrBmHnC/wsLd2QYto8bDgYb3ACiOfEHSItn1QL6O+0K4hsDHJdqu5PvJOgsulqtAXj+SEJpDEQrkk//zmACpzBRw8nPLcR55I6iWvxJXws27XxQ+H+PcJ/Zf7ci4u4pWlBKavDsFlNCEbcovegCItT0LOgPDe7X5o3oOURsqdcugw==,iv:g1NOm+SwqFaNRFOm0bR/n8lcjroowaFS4Hibqxvs4TE=,tag:dp++J3/gwtvt35scl7PSYQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1vea69na6y65tv68elw68vmr5huk3ya0xf3pmrjnxp6ztdy76xfgsn02vu4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4ZWhaRHA3SzZwZVppMjRN
        WjE2YWtvTVFJN1FFb0JmSTJ0WnJYZ0hQWVJRCmpsc3pKTm85ZUF5WFQ5THBROU9F
        L20wb01mL2t1WHZXK1hoaURmaGNkNUUKLS0tIHF0YXBVVzlMalRxUVdsUExrZlJS
        bktPU0VCSXZNemFsakFNeGRjVWJDT3MKW5qhSXqlPHzy8/G6RSPM84Sm3OoRZ99W
        gqL30Z+Z0qsh6C0KlXBf3J9H3uED+gJ2g1IwGANar93LzlVVkP1mxA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-21T10:53:16Z"
  mac: ENC[AES256_GCM,data:bqY10WOtGsSx4mBdc4ALGefl+Oo1PF27Oz0vB2ZHannCBQqW+eauo1yxRDcsjB48ov7XDzFgTqX00OHFOmUxewsCbodyMoswEQnkFJeeXUN65+FgK8qCKqK6NY9FQ4bvEMa9S3hlMotp6cR2LEmNpSVz8RPDH7n/27yruY135hQ=,iv:ORoLSY6ge1Y9829wqp/qF51e8n8T7AoxttoHFpdua/M=,tag:0+10bDN6pi9llwcQGLhFUw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
