# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:Y9DNpB+3yql+65ptOaLISbfaSmhqMI8Dp9YhucQRChI=,iv:jjjpu47VdJ08C8fOedbekwusqaOCdiOzgTfGRAo8bkI=,tag:ZPbNzO9lvuVVPTagrF3CoQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1vea69na6y65tv68elw68vmr5huk3ya0xf3pmrjnxp6ztdy76xfgsn02vu4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaeDRGSzdYdGk2UER1L05j
        eE9SaVBBSWJaeUlkMzJCSXF1QnRXZGhMblg0CkRhSGtXTXRRK0VrbVRCS2RFS2x1
        blFCOE80eEo4SjBBWE8vYVk0a2psOGMKLS0tIGJnRG5IUGtNT253enhvTHZnZVBC
        YWZxeDBoNXQzbGt6ZWE5VWVISUVlZkUKiHVT7VGRnWb5qQn6lUHPlIskVlPtYKv/
        OjVOVCMKbhwEg5IwHvxNPq1bn3rJyLV7Ojxi11sCfvbDF12kHjN5RA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-20T19:32:06Z"
  mac: ENC[AES256_GCM,data:ZCfyT0zAMIv08ZcTO0VKXutsx4JS+JSDoGW+sRmhP+OP5zvNs/uWB6XJyvszHF/obEoCCh2WOgiiJvYTPe0KaFvXoG0w4eXX2Ys8m3cUMMsXCHeivW6/FIbyaBpJvRtQTAo2+xYAAqYEJBfzjR8e91uvF13wWMEMcv+7lPgvO/Q=,iv:8qSlGEmfA1Hc3FzUtsgcJfexmHO3bWCfctzweE8X+F8=,tag:ZoPw13l42ZfR/R/zN88o3Q==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
