# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:DNO7bWULswkMk+s0W2NdSg83n5qKRgcZwmxtwQGoPR8=,iv:HAKOTtsFvZc3EUoyoo8c6sW6QQc8hJqiRwn3kDXlfwo=,tag:+0ao5UJBRNb+yp7ZxJqifw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1vea69na6y65tv68elw68vmr5huk3ya0xf3pmrjnxp6ztdy76xfgsn02vu4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGSENpelIzMUZRZVBTbXNu
        Ykt3aGpsY3BaU2U5ZlYyR1RxcitXTmpucFIwCld1cS90UU5xUHU2NXF1K2xqbm5Q
        SVk5RmxSZ3c1TmZkV2FTSUhCZVhIdXMKLS0tIElZdzdiWEozNVpLaGp6UHQ5OXhG
        WDRtQllob2g1WE92UWtTdVZuemxlWW8KDoqxUyhoeraBHwPn1kYohpGi/zcVrnGk
        seC46VTj2oin2yS2cZEAm5ndK2pm/NQLhGmOfPoiGtdPDSvdg/5Q5w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-20T19:40:54Z"
  mac: ENC[AES256_GCM,data:Urckr47/EwQUrRRHLpcb/g0cg53W/xCGk//QgKbj7q/y2vVhrcyltXzgSPc6fD38A2ZmUc/vbPGnkeNNflixClxMcvdl+UymooEWGuG31d76Llm4Q5oYg8yl0x3qycMBgVwYDjfpxF3BicZ/9YDchzaRJnwSp4RWdTNhHmqlmYE=,iv:Rd3fNufG0iOqPrQdMORgKpdubCi8tpbCquYsshsldN0=,tag:PZBuuhgx/sDYWLJy1VAdEQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
