# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:pf2vJ2SZRUOplCTsR//nc02rXB+EN15ZXG0+zMT1/0U=,iv:3u0DhE6auD9tY+opiWyIoOj4TEvMseYBu8ImbZEW2kI=,tag:IEy/pxeFac0/ysgvEbOoyA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1vea69na6y65tv68elw68vmr5huk3ya0xf3pmrjnxp6ztdy76xfgsn02vu4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZcTlCOGZxbmpSU2lTY3M1
        eWdUY0FENUFrV1cxbHZQMS9WZ3RXTUIxYWpnCno5SVQ3Tk4zOCtxMmQreWYyNFpn
        TVZHMHE1aTYrM1JlbkYrUDlWTGRnZG8KLS0tIEVkV0RWdWljY1YvMkxlS3NLL2F3
        MWpWQkFHcG5ENEVzSEtLdWhnWEowZ0EKzOu2AkPWAmbxrDNiP6Vt0H4K88sdH+CT
        uj7KIm9b9RITnbG2jMqshDYdwf/MDiAlq1oQyLaklvXTbQhGsqD/nA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-20T19:54:06Z"
  mac: ENC[AES256_GCM,data:rQKO0kFLweK6qUfTqEQi/yBivu8hRYbeaDQ3X3sfwoKt+8WtxJAmlG4FyMWmFZbfoWZxY/lruKP/4CY8Q86yViNTS3JcVTY8VSf8rY02dds1vuhbeohCtJM2oIHyLEn4mqn0SZ+1kgfenDonTrAEP0WQq40mCZx+X+wB+/mDOwY=,iv:9ZdXT99oa8psVdC+I0k1M32w1CfbJZNDsZ/P9cEmQ+c=,tag:tSVK0EbD9enUKbTxNZGMgw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
