# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:y6TsBt/lC8xfUMhjqbgq8jB3FMW26nfKKDvflJKmjwKGc82zxA==,iv:KrgINfHZXjSK+LQyMC/S6APgYUurVbzMtDdbbj3AryM=,tag:IwTOGr5mEYQ2l/cdFzBv2A==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1vea69na6y65tv68elw68vmr5huk3ya0xf3pmrjnxp6ztdy76xfgsn02vu4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZaytIZTJpN0tsYmtqT3Mz
        Q01hNDVCNFZ5VDM3dXlxdk16bzVySUQ2OUNvCnZEdksyRnBNMUE0YXlmSUwyclZ4
        bHR2UjN4VFJKL283Ujh2WTI5Um1ZUzgKLS0tIE55eE1SSDRSMjdoajM3VEVRTkZv
        V2lZODJpTTBmd21va2xGSzIyMEtnTDAK6DgQi1Y3uuE0/oABk7X5zH1Yv5DFegKq
        YJQhsOQUGcT/YjxsbRDdRO8H8VADfTJ2LXLiyo0GhbeRqlytT6d2fg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-20T20:46:54Z"
  mac: ENC[AES256_GCM,data:MMh4ZTvCTru+LrnUNgvFXhP6Rc2n0NjyKgFNxX0se0xiz7qE9jDA13MhY3fiSdSDEVjU1rcysjKmlB1oKMuMYaH9uk0mTmY0FxS9Je5APiAjFLZPsEYOCaNFWiG4BkSBjYuuf+OIAXM3sup0CcDzLZV5Lifs42/V8LxbwZcf9Yo=,iv:tKBVYys29APGVYFAqfm8jAyi5bg9R6F0pYWqYDEdX9Y=,tag:OmNhUnt+PjnKilYaZ1DdLA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
