# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:MppaiZqkMwGkbEWm5iNo383GVAsuKcOC9A1vyGjX3LLYyTLNTfi6Bg==,iv:LhrFlBSdhGVDi4Yq8VRJwCPKHw1w0wbqpaXMYbPuod8=,tag:hDrxYZAsqfqT68OOaXW5Kw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1vea69na6y65tv68elw68vmr5huk3ya0xf3pmrjnxp6ztdy76xfgsn02vu4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmT3owbWFRRWNNRUhjY21U
        R29xcEhySTZZY0F1cE5WSzYzNS9wM25ScW1NCjdJQjU1d3Y1SVp2TU05OFE0TURB
        TXRURGpkQ2luUkxRb1loeGxrWllCcHcKLS0tIEVvbE1OSnNVWlNPT3paYWd0UzR1
        NzdlaDVVcXJsdkFLRlFTYTdFaUgxQjQKvn7UucMsKRQTViZSn3YxpEoXmbBsm6Pc
        7HyIHTGUpKyWDP87P5vp2m7BW8edH9puqcyIwV59YqyhNSh4dG7A5g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-21T12:01:53Z"
  mac: ENC[AES256_GCM,data:P9b3+5R9/dRu+JsJdri5xUUtDnz9WJyuNJ3X90bTZUjExUlY8u0KfxIHrE5B0rkmLnzTECUqgwQRZE8cDxAcdOoSQ4WmOw5x6V4LP6HeL2ZWaMR0VcYovG4lKeGoNKe/69uIUgWNtzBIICq/rtu/VZpY6dLD+zgzq0wMnypS8Ec=,iv:dbdJo9oPrqBK6ynmNNpJ7WM+gowM167PmXTKfKehLmw=,tag:VtWzylSKmbLhEe/V1Qlxng==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
