# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:fc6lnzwLgRinUAGo3hil1vCWIfwaLOGVFz03uGofZQgzNgeT5zuI+Q==,iv:YEwC2qu2NMzna9otYEH1ShwHrQBv0cxllR0oVfvj6k8=,tag:BBTx6iiS35uDeV57VQ3D5Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1vea69na6y65tv68elw68vmr5huk3ya0xf3pmrjnxp6ztdy76xfgsn02vu4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVMzZ5a2lORm84WW85US92
        elpyNUp2aVRlWUgvWWRtVXF5YXRSeG1uYmdrCnlnTDFGMG1pK0ZEQ0dFR3ErNmts
        UDBsTGJHaTl3cUhlUE9hQVFkekRpbWMKLS0tIHp0YkNVQXI4QW95MTBxanRtcjNo
        ZlF2VHoxNDB6NzZQeEx6QlVPWVZ6bkUK4nvFkRoz4WFKPOIlmY4qBe7lBvBe43NS
        YQaEHa6VXC+ZWNY4VTrjZ27Gq1QO++IwJom2x6Fn2gZDKR0w7dOa6w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-24T14:00:14Z"
  mac: ENC[AES256_GCM,data:2Na1mSZix5Zl2MjafLcpSr0nLXk6KZurY6a45yYMAH7DtdtEarNVhIo8iRBehY/i7t58w/lFRCXDzyjNKzaveClm3M3QssDPF44/21ts9rngDJkBPf67v2x8fKZiypM1vSzO1sUQSQ053gU27lXojHFTPaiTDsQ7pUWn85UOGcw=,iv:xeHfjUoSkSzi7j+dtcqR0s67e4couqQ+0+LwNnXJEpQ=,tag:wjOZdpPBBsQnCbvK2Jqd5A==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
