# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:i6ADU/BuKxXs1vXOtJ1J3a3zPb/Wq1yaKIrEbwY6xMz66UVDlg==,iv:wNsnKlehdx5hchmEmrFXNycLZs4EVH4N0zf0OyP8+GY=,tag:+pmOldBHghKDp0IZuSjZTA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1vea69na6y65tv68elw68vmr5huk3ya0xf3pmrjnxp6ztdy76xfgsn02vu4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBueXJWZUVQc0MwcERVVXQy
        ZFNGUlNkVmEwanlxSFljN1J0NTVPSEVwcWxZCmxZSGpjSDQ5YkFoY3l1K0VKRUFM
        dHkyRXNmd2NDbEdHVGNYR3I1TXRxd00KLS0tIGlMQklCTnFjWDlvalZkRE85WHpl
        QVVTeElQYXAzbXNsOCs4VzNBcWR6WFEKtdJbH5tDYzOh74O2uqE7dGvtvWY6dl3T
        9hPXSZe6soVV14RP88KHOQPUA8ulY8eo6VfeeqlhZyHhzX4Pm2CQAw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-20T20:28:05Z"
  mac: ENC[AES256_GCM,data:aS/9lnTPId47uHA9OFjOuPH7WksImxEDZPidTUeBzv+ALiwXodNGKINz3rm2PMtprmSeZ4JvqztnPPbsbkAHg07mudrkjw+Kl2jkBBIzgK7qHMFEAlUWGe6SKdqb3noVizYFgMyvXrvcO4M55fUUwhtOI13bTj5eQWOEOLF/kfQ=,iv:Ae5r+U9QXWSkOLM4bbfVUlO4kFA/2HI61kHvhtq+ZB4=,tag:NH71BcJhvNtKHgPVXyC2Gw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
