# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-rook-ceph-cluster-external
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/disabled: "true"
spec:
  # This is needed because we are updating a storageclass object
  force: true
  dependsOn:
    - name: cluster-apps-rook-ceph
  path: ./kubernetes/apps/rook-ceph-external/rook-ceph-external/cluster-external
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: rook-ceph-cluster-external
      namespace: rook-ceph-external
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  # have to manually add decryption since we disabled the standard cluster decryption
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      # Defaults
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cluster-secrets
      # rook-ceph-external specific
      - kind: Secret
        name: rook-ceph-external-vars
