---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "portainer-pvc"
  namespace: network
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "ceph-rdp"
  persistentVolumeReclaimPolicy: Retain
  resources:
    requests:
      storage: "128"
