# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:Bup0noFpNNsAV+Rs8c+VfLN3oQHJNCTFVasbt2wyO7pcqWYYBQ==,iv:NhtqvemvqGrSYKix9xR8xr+zYKLTmWIUUw5r8R6jhWs=,tag:enevEmpuVutPBsVG1BV1Pg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1vea69na6y65tv68elw68vmr5huk3ya0xf3pmrjnxp6ztdy76xfgsn02vu4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQcWNPaXZYSENCbmNjYUVE
        ekdrQ0UzcDUrZnVMSEp1RkJnQ1NyQjdJK2hRCkt2bVRsUzI2SmlxRjNuUzF2MTVr
        bFhSeFJ0cWRMWUJUUHIyamp4NEJjNWcKLS0tIG1jZ0Q4dDlnTEpJRFdWY3RWN3Uy
        a2xHRi9FSi9JdDhtcTFQaGxlS0VpZDgKdn6i3Idv3sEM41CUqmWnWdnOaLpq4xfn
        /1DGH/HNChmz92fG82P06cONNhyAfl8F9fhVnTLYcmTrAiwRE+0RBg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-20T20:28:05Z"
  mac: ENC[AES256_GCM,data:gjQG5czo9IhRxl4gQi8XUdMMZj1qNet82Z4UDUH0VMnbB7diQb29zfNxyvSV6S1uy9DnfjPFfAkTpBHU/TGZI63yB/5yxx61EgOT4SM6sZiJWHPFYKZVA1M7/V79KA+ATZVzRwQo/c7khGUOiwAvMHli+t8Xz926l4o6Blk1Eac=,iv:9xDE+tDHkjhCDPniKIZZZKIROeezLcTYE2hjIhOum5Y=,tag:trhUx+L/E8Ybky1AMP7iTw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
