# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:iyAm4Y+M3SHkUZJT9mcTg7mksIeG5Mpmt9v7xxKOw8J3LRKDNHQMwg==,iv:WSEQu0YYdqzP+pyvAAL0wJHJFG37x6YXqbg+M/U4l8I=,tag:XAzKjxY3cBQqze42nie4fg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1vea69na6y65tv68elw68vmr5huk3ya0xf3pmrjnxp6ztdy76xfgsn02vu4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSTGgvZ1EvaWtOTGhINjVW
        Y2lVSHI5R1kway8xdjNXamtkWUpIQWJ6WmxNCjZ2K0NmSnZ5b2YyUzVyOGNNd1Mz
        ei9aVDE1Vm52ajFPVjlJY0doSVdEdk0KLS0tIHd1RnY5SStTME4ra2J4c0hXQ2hl
        dG9ma0NLdUxsd3EzV3R6by90WHJibE0K/hu4qAp8NO4Z94fqBS6GZ86UTSlgwIdr
        VulWj9VXsEOa15pMXLM48MSwVwrwVnqHdFlhZtZw0Smb3w6dRp6Psg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-21T12:01:53Z"
  mac: ENC[AES256_GCM,data:/Z0zr4sNWB0WTrL2fNyvFYOUAsFOGUQWyWWIDxU8genLAbwlmrLUe5i30ItKGENZ+r+M+YA1rnVPDbtFhH2xi6c/iCQlAkT0om22OFvnWVTY8ISHiuYiCRrszF8XQXZlVJFjyPC0tyP4WnYtlfz72Cbt3uliSK2+datjUKqO/wY=,iv:KhEad4LAtfc2AovF4jE6+lVPzEBRgl/HVUok/wRefcI=,tag:L6kVuqnHgX8lIz44roKYjw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
