apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: portainer
  namespace: flux-system
spec:
  interval: 1h
  path: ./kubernetes/apps/portainer/apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
