---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph-cluster-external
  namespace: rook-ceph-external
spec:
  interval: 15m
  chart:
    spec:
      chart: rook-ceph-cluster
      version: v1.16.4
      sourceRef:
        kind: HelmRepository
        name: rook-ceph
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
    timeout: 60m
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
    timeout: 60m
  uninstall:
    keepHistory: false
    timeout: 5m
  values:
    # Create an external cluster
    cephClusterSpec:
      # Need an empty key here so that it doesn't try to specify a cluster version to check against or
      # block pools will fail.
      cephVersion: {}
      dataDirHostPath: /var/lib/rook-external
      external:
        enable: true
      crashCollector:
        disable: true
      healthCheck:
        daemonHealth:
          mon:
            disabled: false
            interval: 45s

    # Turn on monitoring
    monitoring:
      enabled: true
      externalMgrEndpoints:
        - ip: "${MONITORING_ENDPOINT_MGR_1}"
        - ip: "${MONITORING_ENDPOINT_MGR_2}"
      externalMgrPrometheusPort: 9283

    # Run the ceph-toolbox pod
    toolbox:
      enabled: true

    cephBlockPools: []
    ### CANNOT ADD ANY CEPHBLOCKPOOLS IN THIS HELM CHART. STORAGE CLASS WILL BE ADDED INSTEAD. ###

    cephFileSystems: []
    ### CANNOT ADD ANY CEPHFILESYSTEMS IN THIS HELM CHART. STORAGE CLASS WILL BE ADDED INSTEAD. ###

    cephObjectStores: []
    ### CANNOT ADD ANY CEPHOBJECTSTORES IN THIS HELM CHART. STORAGE CLASS WILL BE ADDED INSTEAD. ###
