apiVersion: v1
kind: Secret
type: kubernetes.io/rook
metadata:
    name: rook-csi-rbd-node
    namespace: rook-ceph-external
stringData:
    userID: ENC[AES256_GCM,data:API/+EZXWlHFQzvo,iv:D357uOrLLqzUJil8ZCJZ0nLWUuWINryZc5kjFq08EMw=,tag:MD5rdb1W8RkwD2DuKAo3YQ==,type:str]
    userKey: ENC[AES256_GCM,data:weHw4UBbDWgliXRb0y1WzBSDJKhdTytQSutMQHqEToEhfuOewRkqZg==,iv:dkmlxFqWVculkOHEWK+j4QUHGSeCIDk3h06U+2nQYDk=,tag:g6HE29nwDLJXJ34LWkwyVA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ghk42c28xewulhvzwnuch55axjfw477ntg8feggyhrx5mlv2y5lqfgfu2q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByMWJ5S3lmWHZZcUR3YkpG
            TG10QlZXam1teURSb3JxK09IS2ZFaUlZV2c0CnNCMEZ0OUJKQ0VuVzdIVHJXQUZS
            U0Q1eVR6TnRLR1NKRTlwTllWZXZVc28KLS0tIHE2Q3dncTRTSGpCaC9uVzU5NGlO
            TndHMFZheTE2czBYdkdGNWIzRlpJYkUKEt8v/oee+8g981Ou00kQtuw504/b7glG
            iXA88v59FL/QTzK0vMU6g9ex79q7XOfwFOv09E0vmZOJNutStgeksQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-19T22:38:25Z"
    mac: ENC[AES256_GCM,data:Ww7DpmwZpkG5kyhO55bwAFby60pPAOaruAVQI+OwqCyJ8a3QTOcrXDcFNfBwu11gRmSzC2et2SFc9kp/aO7U967Zse7k7HEgkW3T3cpjTG8zcwmkGmb+vxFhxOPuI4O+B7NBCdHuDvAtVFAhwsv0NZAhECVxtta8gznM6Pn4xNc=,iv:c2r4vDOnzlCFUagudYcFljK1WWH1yC72nOk79i9/98Q=,tag:U2Fp/r7HrBIIIh6KsVufag==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
