apiVersion: v1
kind: Secret
type: kubernetes.io/rook
metadata:
    creationTimestamp: "2025-02-19T19:54:09Z"
    name: rook-csi-rbd-provisioner
    namespace: rook-ceph-external
stringData:
    userID: ENC[AES256_GCM,data:do1FxWOYIZMAdG2sE514f/S0Ug==,iv:dAplhvBJBxtteN34ePdEux05bRhyq8DB9bJRllA+v0s=,tag:LXUkAxDQVcJikxMVqff6MQ==,type:str]
    userKey: ENC[AES256_GCM,data:T/M+SKIG0W2FQkgGU7cwVoaeW665kbSoiDT3Gofp+Qcb0uDV30XL3Q==,iv:O9NIEZ6+tsj/OlxGl088E7t4ZOVH9NgiO0RV5wJ8bHI=,tag:svGyVCHQYj0a7ubCQa1bRA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ghk42c28xewulhvzwnuch55axjfw477ntg8feggyhrx5mlv2y5lqfgfu2q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzUFNVcWhYV1pyOFppS2dq
            eGxQUnNMSitpbUU1ZVRnSlpPNnFPYm1BS1RFCjFka28xK2NvZnFaMC8vcEQxK1JF
            R3hLVVBVSUM2TDlsRHRzZUgrUjlsb0UKLS0tIEhQTy8vUTBuNFAveFFqc0JZZUI4
            OUNNeGx2dTg3VEh6ZlpVTGtXQXcxcmMKr3ERXAPRHa4lokAAUkzb+U6wrW4+DmTW
            zGbCW0wqaIaY9rMBKr6TDBjQq2i/kYeiOVi60wDhPr/kEpoSIxUFyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-19T22:39:42Z"
    mac: ENC[AES256_GCM,data:HQnRNHIyzF9IyHbkukCDJGcUiV8c0a0vstBua5OdqeUD2ognlhSzage8AJqnhM1F7JiN6cTfUACUw+29P0aSWZag0lLgvFF0YKOxQcAf0O75wqCrPRrgC9ojMkZyD/1UJbGZql4TXafLGKmvKfiBDTrGc+GR1BMZUT+8p8zGV6A=,iv:MvqFypvehFqkqlwwSZ3htSg88CufFU2Ib9GuCEgu/kM=,tag:P6GuVDc+ggn5PiJT4+cKiA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
