apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:cCJiOaM8dPU30A==,iv:3f4y4M3ybtGm3oHiTkzvLuL01Tmz273FA1Y3JctEcfI=,tag:lgvqAA4Rl18mYLyLSC2X0w==,type:str]
  SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:s/3SPt7KdmTIQgbCSMmCDctvV6L9s2pAh1NVQpsVLo0kyyyT,iv:aRpLTMcBO83UbVzfWke+scGnFACJADgtg8RpcW9OTc0=,tag:LXckIJwre6GUXiHH4CY5cw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1vea69na6y65tv68elw68vmr5huk3ya0xf3pmrjnxp6ztdy76xfgsn02vu4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNanlkQXB4dkR0U016VjBF
        THpVVzU2SU8rUTM2RTA4b1g4WHNlMXc3TjM4CjdZQ2NVQjB3SXY4R0cyZlBwUlBx
        RkMrUVBjREc5aWIvVmZsd3U0ZVVKTm8KLS0tIFRPTWJ5YlYxSVorcThVZHJVa3dE
        TzFqdHcxOWFBYXZqeXJGN0lRNTBnMzgKvytQS7+4TL8sGCwp6yCLs8iCiikLlwxc
        AYnJI9WvOiEqUD+CjfC7wZmvC5qwXQrDardzz1HC1M6lX5SSN+uIAA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-20T19:01:03Z"
  mac: ENC[AES256_GCM,data:3I+dP/jaJfwb0cCtFYQDYsQ0/3wlKOg25NJUQoR2prioC2PkohMf0CWlejzAx3OS6HkTLX4sf0+cnA+DsiTrrJwQik/Ee2En+9A5QbnKawT+4m5JaOPtTjKZFXC4hIdMGWY1TOyrGIneXwkADvjfDNcY+C4aKMrl6D3NFdnHsOs=,iv:yUunRTyPfdqL+5qhj7Fj5IAx/jPktZmBThKG6UTAqos=,tag:c3ff8HGE0lKof6w4otAtaw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
