apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:QidsGFiW6AHT2w==,iv:O6RnjTERCbvzvd5rs5xe2b554GkhLmu6EwJc9+kWpKA=,tag:Uc9r7W87E7tt74sZadUvaQ==,type:str]
  SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:iCjq2qPdLPmrOTVcjx7+rab33Y2yshNiuWFpT5+jdv7lQ9YM,iv:4cHCrMb3LQge0BP5JW1/EurUc4Rxa8AfMRHdK/hDrbo=,tag:kSUnbcEw7jOIKYqf7ZcdPA==,type:str]
  SECRET_RANCHER_ADMIN_PASSWORD: ENC[AES256_GCM,data:L/tdaPGr06NqsNjynaM=,iv:NgLneEWtb8Z0TKkWFR66BDMwuBxe1UEO/AIOAVVL/zk=,tag:66bHPmhqaCp1BfDIoc5JGw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1vea69na6y65tv68elw68vmr5huk3ya0xf3pmrjnxp6ztdy76xfgsn02vu4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsRU9RcXVoVUhnamJuOWo3
        TmNyS05FYlBRa3RmUlVGODNudmdTK2lUckRFCmhiNzlpZEE3aEdLYkozVVhhVGFl
        Vks1UFROb1FLQmxJcjV2QUoxelZYL2MKLS0tIDExUlJhT3VIRk85MmJSUzJ5UVlX
        M1JGVUFlSGs0cHhLTzRhamJiMVVBRXcKso6t6urf6fUdUGnhTng4bLgd5yooSNFS
        TFLFKZNOoIUxNpWXwBb9ScSVmeGL47MS6aNSPE1KJ3gy9XgqVPhiDA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-21T14:51:00Z"
  mac: ENC[AES256_GCM,data:fDoayuX6mwEHGHtcM5QJ3VMhfLUuqE14mbdeHq9HjguzrIMbLRuWX8VSlOpQ2iM2rkn0+KX/+luhM/yyFtylHWF6QCUm3QLPlZEFqx04eJhpfVU22K1w9g5b0kQNQHj0wtEHlxnj9KzSYPTZCoe5/qHNuCLeUJhsnjtJ4JeVa+Y=,iv:piEeofVtHHW09HlhNuGnu+E2OatB5En2fQrZNjcvBs8=,tag:a0YUNXEkPPyKzcDOhM9/WQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
