apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:Qwf0BT10WDsVsw==,iv:8w1cJWX6OxznSrwyjyL/f9hrTenKQ3FPUx6mRJmuzd0=,tag:fSPVCTCicgSUCCUMyqwXgQ==,type:str]
  SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:gBVrTW6gYUKkuG4bWDpz3ZN+HmdjOWkmO3Xr7OkWU0V9OoyG,iv:+KjVN1ZCpTOv2nQKD2htR51Pdj+cHu8TEeXF0jLFLck=,tag:x3xIbdGytmUPeYXX43TRyg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1vea69na6y65tv68elw68vmr5huk3ya0xf3pmrjnxp6ztdy76xfgsn02vu4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjTjBMSE5QWG15Q1hjczIw
        ZTdITXRJdXIwZjVXS3ZmNElqQys0VnJzZmdjCkhuRk9GUzJhMm16ZDhrb1VOU3lZ
        L1BaMFZHQk5LdlFWdnRZWnhTa2I4eWcKLS0tIE56VTdJVmJEZ05HUEtDSmN0ZnY5
        MDlwRTZySHVjNkpaUUNLWFdvcC9qazQKkspmzFA04bP/MbgL/KO0GHWN1/uJmrON
        haI+rreLq++Dwb/nkhdlxmcW4JNEzpiJhaeGLN7lVXYYyTZ/U0tdNQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-21T12:01:53Z"
  mac: ENC[AES256_GCM,data:JpU2nSL+uhUf1WDkVLc6/3OJTb0mzfeSVY8oFVA7dbmpI1ZpTPIIs8TzUuRyJ67PweKtF8H4Awf67mGOyIGcBDcOutx5JafiNAh1JOmEAU5wlvbvG/BMr/7u5J2I9EP5gtyOcROutBIhiD/Ce6sYa5Xm0gSxZmDsNXDLWRrpvq4=,iv:nOkIA+wOlHcznXVEwNts/g2FrmjTehPPAlHRpUjyN6c=,tag:I8tyhjgh/Wo2ypgQN3fNPA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
