apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:6XjmgX3GjnitLA==,iv:r3Jw3BVptnfKdpuWq7FatfqCiTvZeG3vS7O93qfGos8=,tag:uBsHDJ22uEyHH0/+WWekCw==,type:str]
  SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:1N51GAiRwXngBacYMPWzUUnjQWOrqlPK8zyaaEX9GOSIvR+r,iv:0AIcvQ1BvcgnZIlLWvbq5oU9N4pfENrOCbtIMnUZP84=,tag:0isgXc/dHr6PFB7zJPoeeA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1vea69na6y65tv68elw68vmr5huk3ya0xf3pmrjnxp6ztdy76xfgsn02vu4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCWlF1ZEt0c2w5VUs1TWdx
        L045S0k4TXNkMnREOUhkR0dMSDZ2WWhGcWdrCk5MVzJrZHFiT0JuaTZlM2ZHck1i
        NGpxT3J3UzlnY2RUQi96UTZxOCtUUEUKLS0tIHVaNFNvT25oamZJMkVYcmxwem1F
        cTJ5R1I4b2ZYb2l5Sk5rVXVYcjdCM0kKSaobDkYh8FELVpEoE0tZg0y/8n2VVwL3
        yKVgPWRw5j2+4BX7/E7w9tX3UMH+1JDWpf48/8LTyXqUzTPCcNTETw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-20T18:46:03Z"
  mac: ENC[AES256_GCM,data:el98qX6XbYdTpYkbZN6rzme1aKNdjjzAJzSxplR+e8fL3A3rQfrj7ZXCzDohVPrte4fW8GvP+6BqlHlmqHZV/PEErHIaruYUPAUBHRIDuyYO0GdBwOtJPddvNu1DXQOzh7bHyDjNZ2cL+x6i794bMwVIklYWmpncqMkaWsyyvFs=,iv:nlE6RcFe2mGLGthRQO/nOHZb8+cqfqnP5uRGih9qVuA=,tag:PjriNkVZkB4rggUbKAZxpA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
