apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:YXBxhYfrl8ozrdmueeIF6VxfIThT1i0VNdyzuO9ga4wxjIHjoQ0YqlLY+lsQyjYO4SJeY5ahs+SJK3xU9q7bFPKDdK6Fp9vnCGNd,iv:NNdgj2yuCCIOihBCjDsxTQsJ1TPPk0XiAHrx8gOHJpI=,tag:flqkR2+c1+zs4XPdeVwGbQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1vea69na6y65tv68elw68vmr5huk3ya0xf3pmrjnxp6ztdy76xfgsn02vu4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTZCsvVkRMU3RiSkNTZ1Nx
        SS9Nb3dtNE1SM05yMDB2MThXQ0dYREhUOWtvCnl1QmliNVNoaE9VVjAzT2dGT282
        bjJjUDBXQ2ttU3c3TE9BZE42RlhYaUEKLS0tIE1BdnBubnZiN085cFpIVlhVRGhE
        aVNsSC9YUlA3VURrem9BOE1rRGc0dWMKVkN4D/PiCt68CpyEl//2XP/v9amWYArI
        FSF4ibDfdFNL0nvB89bSFFAU/ZPetqhXNFQl02Ef/bJsWwUNiTpDPQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-24T14:00:14Z"
  mac: ENC[AES256_GCM,data:vtstkDNOQo37RTV1rfJgN2i8XIkXQOLiwUTFN36K+He38TszQwzB1rsLXT/7CpQvKnUUIuVLljtTBoJWQDdUBz2NadVhK6T5g+6ww/IHP0eViKYlZNyBkoFGq6CV8kfzZRIkAn3alxW9V5kdaMNcdu34DVxq+bNYaTJ433QzKAk=,iv:a2aVgY+8HWlHY5SEi15y+1jcgY8JTIlxDMAKy74jfaU=,tag:+/VW+h7J9CTj7YufdoMJAg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
