apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:pYruZmHkitIddErjr959qXJY2L5+mqPLFtbKyp7aWvEdxs1TQuhEnZdk35TNuyB5VFVbE2AR2QyDcianVuiMsFfWuqbihUnt55JU,iv:T4HeFhDfk93lPIHHENoUFhewBe10xKqOLiPNal1eXBc=,tag:0oEjKf1vfdqFnovytk1MUA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1vea69na6y65tv68elw68vmr5huk3ya0xf3pmrjnxp6ztdy76xfgsn02vu4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAraDhZN3hGcStJckZNWTZF
        UmJHU3ovbjdXNUVad2RnV1RiS2MxajhOdlJvClVOeTVML2xRQlFIaXFuak9ZNWd1
        QlN2a25jekVXNzdmMkhJeXVvWmFDclUKLS0tIHA5L05rZHgxSnhZeWp1cFRuMmpQ
        Wm51UEZJK0JxYnZnNCt3a0hxVXhaTEEK/3OqIo4kZbMBaUagD8wMKLDN14ExSHnD
        F7fUHAm783164q+KjIFyzXvWgGogfICyddr3zwKWgfqZEjaqvxZ0Hg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-20T20:46:54Z"
  mac: ENC[AES256_GCM,data:1fInOsC1n5A7IUku7d463jOGKZSh7nEs1d02azO6gipFwcqAlnhgljqtK/D3rTvDpSgIOCvOrgPSqwB/duBYlMGY6f9oKr32xZ76pF2gJ35828Vn2IIpGXKU+yFQulOahEMEUv6+PlcbIC7WmTf8fg8hExvQOcY4GcC/GcagJ3U=,iv:hUqp5N6WxwDQ4SVzBzgwOOXhPL0TmxQhRVOnVscihQY=,tag:BSTc+00mDBewQysRg7Zwtw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
