---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph-operator
  namespace: rook-ceph
spec:
  interval: 15m
  chart:
    spec:
      chart: rook-ceph
      version: v1.16.4
      sourceRef:
        kind: HelmRepository
        name: rook-ceph
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
    timeout: 60m
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
    timeout: 60m
  uninstall:
    keepHistory: false
    timeout: 5m
  values:
    crds:
      enabled: true
    pspEnable: false
    monitoring:
      enabled: true
    resources:
      requests:
        cpu: 10m
        memory: 128Mi
    hostpathRequiresPrivileged: true
    csi:
      provisioner:
        image: registry.k8s.io/sig-storage/csi-provisioner:v5.2.0
